config/routes.rb
Brainreserve::Application.routes.draw do
  
  resources :employees

  root :to => "pages#home"
  
  match '/admin' => 'pages#index'
   match '/pages/show_article' => 'pages#show_article'
  match 'culturepulse_search' => 'pages#culturepulse_search'
   match '/culturepulse/article' => 'pages#culturepulse_article'

   match '/culturepulse' => 'pages#culturepulse'
  
  devise_for :administrators, :path_prefix => 'd'

  resources :pages do
  	resources :assets
	resources :snippets
	
  end
  resources :talentbank_members
  resources :articles do
    resources :comments
  end

end

app/models/comment.rb
class Comment
  include Mongoid::Document
  field :name, :type => String
  field :content, :type => String
  
  embedded_in :article
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  # GET /comments
  # GET /comments.xml
  def index
     @article =  Article.find(params[:article_id])
  
    @comments = @article.comments.all

    respond_to do |format|
      format.html # index.html.erb
      format.xml  { render :xml => @comments }
    end
  end

  # GET /comments/1
  # GET /comments/1.xml
  def show
     @article =  Article.find(params[:article_id])
  
    @comment = @article.comments.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.xml  { render :xml => @comment }
    end
  end

  # GET /comments/new
  # GET /comments/new.xml
  def new
     @article =  Article.find(params[:article_id])
  
    @comment = @article.comments.new

    respond_to do |format|
      format.html # new.html.erb
      format.xml  { render :xml => @comment }
    end
  end

  # GET /comments/1/edit
  def edit
     @article =  Article.find(params[:article_id])
  
    @comment = @article.comments.find(params[:id])
  end

  # POST /comments
  # POST /comments.xml
  def create
    @article =  Article.find(params[:article_id])
    @comment = @article.comments.new(params[:comment])

    respond_to do |format|
      if @comment.save
        format.html { redirect_to(article_comments_url(@article), :notice => 'Comment was successfully created.') }
        format.xml  { render :xml => @comment, :status => :created, :location => @comment }
      else
        format.html { render :action => "new" }
        format.xml  { render :xml => @comment.errors, :status => :unprocessable_entity }
      end
    end
  end

  # PUT /comments/1
  # PUT /comments/1.xml
  def update
    @article =  Article.find(params[:article_id])
    @comment = @article.comments.find(params[:comment])

    respond_to do |format|
      if @comment.update_attributes(params[:comment])
        format.html { redirect_to(article_comments_url(@article), :notice => 'Comment was successfully updated.') }
        format.xml  { head :ok }
      else
        format.html { render :action => "edit" }
        format.xml  { render :xml => @comment.errors, :status => :unprocessable_entity }
      end
    end
  end

  # DELETE /comments/1
  # DELETE /comments/1.xml
  def destroy
    @article = Article.find(params[:article_id])
    @comment = @article.comments.find(params[:id])
    @comment.destroy

    respond_to do |format|
      format.html { redirect_to(article_comments_url(@article)) }
      format.xml  { head :ok }
    end
  end
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/views/comments/_form.html.erb
<%= form_for([@article, @comment]) do |f| %>
  <% if @comment.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@comment.errors.count, "error") %> prohibited this comment from being saved:</h2>

      <ul>
      <% @comment.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br />
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :content %><br />
    <%= f.text_area :content %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/comments/edit.html.erb
<h1>Editing comment</h1>

<%= render 'form' %>

<%= link_to 'Show', @comment %> |
<%= link_to 'Back', comments_path %>

app/views/comments/index.html.erb
<h1>Listing comments</h1>

<table>
  <tr>
    <th>Name</th>
    <th>Content</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @comments.each do |comment| %>
  <tr>
    <td><%= comment.name %></td>
    <td><%= comment.content %></td>
    <td><%= link_to 'Show', article_comment_path(@article, comment) %></td>
    <td><%= link_to 'Edit', edit_article_comment_path(@article, comment) %></td>
    <td><%= link_to 'Delete', article_comment_path(@article, comment), :confirm => 'Are you sure?', :method => :delete %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Comment', new_article_comment_path(@article) %>

app/views/comments/new.html.erb
<h1>New comment</h1>

<%= render 'form' %>

<%= link_to 'Back', article_comments_path(@article) %>

app/views/comments/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Name:</b>
  <%= @comment.name %>
</p>

<p>
  <b>Content:</b>
  <%= @comment.content %>
</p>


<%= link_to 'Edit', edit_article_comment_path(@article, @comment) %> |
<%= link_to 'Back', article_comments_path(@article) %>