config/routes.rb
Brainreserve::Application.routes.draw do
  
  resources :employees

  root :to => "pages#home"
  
  match '/admin' => 'pages#index'
   match '/pages/show_article' => 'pages#show_article'
  match 'culturepulse_search' => 'pages#culturepulse_search'
   match '/culturepulse/article' => 'pages#culturepulse_article'

   match '/culturepulse' => 'pages#culturepulse'
  
  devise_for :administrators, :path_prefix => 'd'

  resources :pages do
  	resources :assets
	resources :snippets
	
  end
  resources :talentbank_members
  resources :articles do
    resources :comments
  end

end

app/models/article.rb
class Article
  include Mongoid::Document
  include Mongoid::Paperclip
  include Mongoid::Timestamps
  include Mongoid::FullTextSearch

  
  field :name, :type => String
  field :description, :type => String
  field :description2, :type => String
  
  field :content, :type => String
  field :category, :type => String
  field :is_featured, :type => Boolean, :default => false
  field :the_date, :type => DateTime
  embeds_many :comments
  has_mongoid_attached_file :article_photo
  has_mongoid_attached_file :link_photo
  validates :name, :uniqueness => true
  validates :description, :presence => true
  validates :content, :presence => true
  
  fulltext_search_in :name, :description, :description2, :content	

end

app/controllers/articles_controller.rb
class ArticlesController < ApplicationController
  # GET /articles
  # GET /articles.xml
  def index
    @articles = Article.all

    respond_to do |format|
      format.html # index.html.erb
      format.xml  { render :xml => @articles }
    end
  end

  # GET /articles/1
  # GET /articles/1.xml
  def show
    @article = Article.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.xml  { render :xml => @article }
    end
  end

  # GET /articles/new
  # GET /articles/new.xml
  def new
    @article = Article.new

    respond_to do |format|
      format.html # new.html.erb
      format.xml  { render :xml => @article }
    end
  end

  # GET /articles/1/edit
  def edit
    @article = Article.find(params[:id])
  end

  # POST /articles
  # POST /articles.xml
  def create
    @article = Article.new(params[:article])

    respond_to do |format|
      if @article.save
        format.html { redirect_to(@article, :notice => 'Article was successfully created.') }
        format.xml  { render :xml => @article, :status => :created, :location => @article }
      else
        format.html { render :action => "new" }
        format.xml  { render :xml => @article.errors, :status => :unprocessable_entity }
      end
    end
  end

  # PUT /articles/1
  # PUT /articles/1.xml
  def update
    @article = Article.find(params[:id])

    respond_to do |format|
      if @article.update_attributes(params[:article])
        format.html { redirect_to(@article, :notice => 'Article was successfully updated.') }
        format.xml  { head :ok }
      else
        format.html { render :action => "edit" }
        format.xml  { render :xml => @article.errors, :status => :unprocessable_entity }
      end
    end
  end

  # DELETE /articles/1
  # DELETE /articles/1.xml
  def destroy
    @article = Article.find(params[:id])
    @article.destroy

    respond_to do |format|
      format.html { redirect_to(articles_url) }
      format.xml  { head :ok }
    end
  end
end

app/helpers/articles_helper.rb
module ArticlesHelper
end

app/views/articles/_form.html.erb
<script type="text/javascript" src="/javascripts/tinymce/jscripts/tiny_mce/tiny_mce.js"></script>
<script type="text/javascript">
tinyMCE.init({
        // General options
        mode : "textareas",
        theme : "advanced",
        plugins : "pagebreak,style,layer,table,save,advhr,advimage,advlink,emotions,iespell,inlinepopups,insertdatetime,preview,media,searchreplace,print,contextmenu,paste,directionality,fullscreen,noneditable,visualchars,nonbreaking,xhtmlxtras,template",
	editor_selector : "mceEditor",
        editor_deselector : "mceNoEditor",
        // Theme options
        theme_advanced_buttons1 : "save,newdocument,|,bold,italic,underline,strikethrough,|,justifyleft,justifycenter,justifyright,justifyfull,|,styleselect,formatselect,fontselect,fontsizeselect",
        theme_advanced_buttons2 : "cut,copy,paste,pastetext,pasteword,|,search,replace,|,bullist,numlist,|,outdent,indent,blockquote,|,undo,redo,|,link,unlink,anchor,image,cleanup,help,code,|,insertdate,inserttime,preview,|,forecolor,backcolor",
        theme_advanced_buttons3 : "tablecontrols,|,hr,removeformat,visualaid,|,sub,sup,|,charmap,emotions,iespell,media,advhr,|,print,|,ltr,rtl,|,fullscreen",
        theme_advanced_buttons4 : "insertlayer,moveforward,movebackward,absolute,|,styleprops,|,cite,abbr,acronym,del,ins,attribs,|,visualchars,nonbreaking,template,pagebreak",
        theme_advanced_toolbar_location : "top",
        theme_advanced_toolbar_align : "left",
        theme_advanced_statusbar_location : "bottom",
        theme_advanced_resizing : true,

        // Example content CSS (should be your site CSS)
        content_css : "css/example.css",

        // Drop lists for link/image/media/template dialogs
        // template_external_list_url : "js/template_list.js",
        // external_link_list_url : "js/link_list.js",
        // external_image_list_url : "js/image_list.js",
        // media_external_list_url : "js/media_list.js",

        // Replace values for the template plugin
        template_replace_values : {
                username : "Some User",
                staffid : "991234"
        }
});
</script>

<%= form_for(@article, :html => {:multipart => true}) do |f| %>
  <% if @article.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@article.errors.count, "error") %> prohibited this article from being saved:</h2>

      <ul>
      <% @article.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br />
    <%= f.text_field :name %>
  </div><br/>
  <div class="field">
    <%= f.label :description %><br />
    <%= f.text_area :description %>
  </div><br/>
<div class="field">
    <%= f.label 'Description 2 (if necessary)' %><br />
    <%= f.text_area :description2 %>
  </div><br/>
<div class="field">
    <%= f.label :is_featured %><br />
    <%= f.check_box :is_featured %>
  </div><br/>

<div class="field">
    <%= f.label :category %><br />
   <select id="article_category" name="article[category]">
      <option value="home">Home</option>
      <option value="what_we_do">What We Do</option>
      <option value="trendbank">Trend Bank</option>
      <option value="publications">Publications</option>
      <option value="clients_and_case_studies">Case Studies</option>
      <option value="talentbank_salons">Talentbank Salons</option>
      <option value="talentbank">Talentbank</option>
      <option value="popcorn_report_live">Popcorn Report Live</option>
      <option value="futurevision">Future Vision</option>
      <option value="trendtrek">TrendTrek</option>
      <option value="culture_pulse_blog">Culture Pulse Blog</option>
      <option value="speeches">Speeches</option>
      <option value="consumer_insights">Consumer Insights</option>
      <option value="brand_positioning">Brand Positioning</option>
      <option value="futurescape">Futurescape</option>
      <option value="inculture">Inculture</option>
      <option value="about_us">About Us</option>
      <option value="employee">Biographies</option>

      <option value="">None</option>
    
    </select>
  </div>
  <div class="field">
    <%= f.label :content %><br />
    <%= f.text_area :content, :class => 'mceEditor' %>
  </div>
 <div class="field">
    <%= f.label 'Article Photo' %><br />
    <%= f.file_field :article_photo %>
  </div>
 <div class="field">
    <%= f.label 'Link Photo' %><br />
    <%= f.file_field :link_photo %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/articles/edit.html.erb
<h1>Editing article</h1>

<%= render 'form' %>

<%= link_to 'Show', @article %> |
<%= link_to 'Back', articles_path %>

app/views/articles/index.html.erb
<center>
<img src="/images/header/logo_178_41.png" /><br/>

<h1>Listing Content Snippets</h1></center>

<table>
  <tr>
    <th>Name</th>
    <th>Description</th>
   <th>Category</th>
   <th>Is Featured?</th>
   <th></th>
    <th></th>
    <th></th>
  </tr>

<% @articles.each do |article| %>
  <tr>
    <td><%= article.name %></td>
    <td><%= article.description %></td>
    <td><%= article.category %></td>
    <td><%= article.is_featured %></td>
    <td><%= link_to 'View', article %></td>
    <td><%= link_to 'Edit', edit_article_path(article) %></td>
    <td><%= link_to 'Delete', article, :confirm => 'Are you sure?', :method => :delete %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Article', new_article_path %>

app/views/articles/new.html.erb
<h1>New article</h1>

<%= render 'form' %>

<%= link_to 'Back', articles_path %>

app/views/articles/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Name:</b>
  <%= @article.name %>
</p>

<p>
  <b>Description:</b>
  <%= @article.description %>
</p>
<p>
  <b>Category:</b>
  <%= @article.category %>
</p>
<p>
  <b>Is Featured:</b>
  <%= @article.is_featured %>
</p>
<p>
  <b>Content:</b>
  <%= @article.content.html_safe %>
</p>
<p>
  <b>Date:</b>
  <%= @article.the_date %>
</p>
<p>
  <b>Article Photo:</b>
  <%= image_tag @article.article_photo.url %>
</p>


<p>
  <b>Link Photo:</b>
<%= image_tag @article.link_photo.url %>
</p>

<%= link_to 'Comments', article_comments_path(@article) %>

<%= link_to 'Edit', edit_article_path(@article) %> |
<%= link_to 'Back', articles_path %>