config/routes.rb
Brainreserve::Application.routes.draw do
  
  resources :employees

  root :to => "pages#home"
  
  match '/admin' => 'pages#index'
   match '/pages/show_article' => 'pages#show_article'
  match 'culturepulse_search' => 'pages#culturepulse_search'
   match '/culturepulse/article' => 'pages#culturepulse_article'

   match '/culturepulse' => 'pages#culturepulse'
  
  devise_for :administrators, :path_prefix => 'd'

  resources :pages do
  	resources :assets
	resources :snippets
	
  end
  resources :talentbank_members
  resources :articles do
    resources :comments
  end

end

app/views/pages/_form.html.erb
<%= form_for(@page) do |f| %>
  <% if @page.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@page.errors.count, "error") %> prohibited this page from being saved:</h2>

      <ul>
      <% @page.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>
 <div class="field">
    <%= f.label :name %><br />
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :description %><br />
    <%= f.text_area :description %>
  </div>
 

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/pages/culturepulse.html.erb

<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml">
<head>
<meta http-equiv="Content-Type" content="text/html; charset=UTF-8" />
<title>Culture Pulse Blog</title>
<link rel="stylesheet" href="/stylesheets/style_cp.css" type="text/css">
</head>

<body>

<div id="cp_linewrapper">
<div id="cp_logo">


    <div style="text-align:center; width:1216px; margin-left:auto; margin-right:auto;">
    <img id="Image-Maps_7201202090253555" src="/images/header_logo_culturepulse.png" usemap="#Image-Maps_7201202090253555" border="0" width="1216" height="177" alt="" />
    <map id="_Image-Maps_7201202090253555" name="Image-Maps_7201202090253555">
    <area shape="rect" coords="58,22,308,91" href="/" alt="" title=""    />
     </map>
   

    </div>
            


</div>
<div id="cp_areafill">

<div id="cp_maincontentarea">
	<div id="cp_mainarticle" style="background:#412226;">
		<div id="cp_mainarticleimage"><img id="cp_mainarticleimage" src="<%= @articles[0].article_photo.url if @articles[0].present? %>" border="0" alt="Brain Reserve Culture Pulse" /></div>
        <div id="cp_mainarticlecopy">
        	<div id="cp_mainarticledate"><%= @articles[0].updated_at.strftime('%m-%d-%y') if @articles[0].present? %></div>
            <div id="cp_mainarticletitle"><a href="/culturepulse/article?name=<%= CGI.escape(@articles[0].name) if @articles[0].present?  %>" id="cp_mainarticletitle"><%= @articles[0].name if @articles[0].present? %> </a></div>
            <div class="cp_seemore"><a href="/culturepulse/article?name=<%= CGI.escape(@articles[0].name) if @articles[0].present?  %>">SEE MORE</a></div>
            <div class="cp_excerpt">
            	<%= @articles[0].description if @articles[0].present? %>
            </div><!-- end cp_excerpt -->
        </div><!-- end cp_mainarticlecopy -->
        
	</div><!-- end cp_mainarticle -->
   <div class="cp_subarea">
    <div class="cp_subarticlearea">
    	<div class="cp_subarticleimage" style="background:#3c2c19">
        	<div id="cp_mainarticledate"><%= @articles[1].updated_at.strftime('%m-%d-%y') if @articles[1].present? %></div>
            <div id="cp_subarticletitle"><%= @articles[1].name if @articles[1].present? %></div>
            <div class="cp_seemore"><a href="/culturepulse/article?name=<%= CGI.escape(@articles[1].name) if @articles[1].present?  %>">SEE MORE</a></div>
            
        </div>
    <div class="cp_subexcerpt">	<%= @articles[1].description if @articles[1].present? %></div>
    </div><!-- end cp_subarticlearea -->
    
     <div class="cp_subarticlearea">
    	<div class="cp_subarticleimage" style="background:#2e3740">
        	<div id="cp_mainarticledate"><%= @articles[2].updated_at.strftime('%m-%d-%y') if @articles[2].present? %></div>
            <div id="cp_subarticletitle"><%= @articles[2].name if @articles[2].present? %></div>
            <div class="cp_seemore"><a href="/culturepulse/article?name=<%= CGI.escape(@articles[2].name) if @articles[2].present?  %>">SEE MORE</a></div>
            
        </div>
    <div class="cp_subexcerpt"> <%= @articles[2].description if @articles[2].present? %></div>
    </div><!-- end cp_subarticlearea -->
    
     <div class="cp_subarticlearea">
    	<div class="cp_subarticleimage" style="background:#3c2c19; <% if @articles[3].present? then %> background:url('<%= @articles[3].link_photo.url %>')<% end %>">
        	<div id="cp_subdate2"><%= @articles[3].updated_at.strftime('%m-%d-%y') if @articles[3].present? %></div>
            <div id="cp_subtitle2"><%= @articles[3].name if @articles[3].present? %></div>
            <div class="cp_subseemore2"><a href="/culturepulse/article?name=<%= CGI.escape(@articles[3].name) if @articles[3].present?  %>">SEE MORE</a></div>
            
        </div>
    <div class="cp_subexcerpt"></div>
    </div><!-- end cp_subarticlearea -->
    
    <div class="cp_subarticlearea">
    	<div class="cp_subarticleimage" style="background:#472c2d">
        	<div id="cp_mainarticledate"><%= @articles[4].updated_at.strftime('%m-%d-%y') if @articles[4].present? %></div>
            <div id="cp_subarticletitle"><%= @articles[4].name if @articles[4].present? %></div>
            <div class="cp_seemore"><a href="/culturepulse/article?name=<%= CGI.escape(@articles[4].name) if @articles[4].present?  %>">SEE MORE</a></div>
            
        </div>
    <div class="cp_subexcerpt"><%= @articles[4].description if @articles[4].present? %></div>
    </div><!-- end cp_subarticlearea -->
    
      <div class="cp_subarticlearea">
    	<div class="cp_subarticleimage" style="background:#3c2c19; <% if @articles[5].present? then %> background:url('<%= @articles[5].link_photo.url %>')<% end %>">
        	<div id="cp_subdate2"><%= @articles[5].updated_at.strftime('%m-%d-%y') if @articles[5].present? %></div>
            <div id="cp_subtitle2"><%= @articles[5].name if @articles[5].present? %></div>
            <div class="cp_subseemore2"><a href="/culturepulse/article?name=<%= CGI.escape(@articles[5].name) if @articles[5].present?  %>">SEE MORE</a></div>
            
        </div>
    <div class="cp_subexcerpt"></div>
    </div><!-- end cp_subarticlearea -->
    
      <div class="cp_subarticlearea">
    	<div class="cp_subarticleimage" style="background:#3e4428">
        	<div id="cp_mainarticledate"><%= @articles[6].updated_at.strftime('%m-%d-%y') if @articles[6].present? %></div>
            <div id="cp_subarticletitle"><%= @articles[6].name if @articles[6].present? %></div>
            <div class="cp_seemore"><a href="/culturepulse/article?name=<%= CGI.escape(@articles[6].name) if @articles[6].present?  %>">SEE MORE</a></div>
            
        </div>
    <div class="cp_subexcerpt"><%= @articles[6].description if @articles[6].present? %></div>
    </div><!-- end cp_subarticlearea -->
   </div><!-- end cp_subarea -->
</div><!-- end cp_maincontentarea -->


</div><!-- end cp_areafill -->




<div id="cp_sidebar">
	<div class="cp_sidesection">
		<div class="cp_sidebarcircle"></div>
        <div class="cp_sidesectiontitle">SUBSCRIBE</div>
        <div class="cp_sidesubtitle">Get our daily newsletter</div>
        <div id="cp_subscribefield"><form>
<input type="text" name="field" class="subscribefield" value="" />
</form></div>
		<div class="cp_signup"><a href="#" target="_self"><img src="/images/sidebar_subscribe_signup_btn_103-27.jpg" border="0" /></a></div>
	</div><!-- end cp_sidesection -->
    
<div class="cp_sidesection">
		<div class="cp_sidebarcircle"></div>
        <div class="cp_sidesectiontitle">ARCHIVES</div>
        <div class="cp_sidesubtitle"><br />OCTOBER 2011<br />
        SEPTEMBER 2011<br />AUGUST 2011<br />JULY 2011<br />JUNE 2011<br />MAY 2011<br />APRIL 2011<br />MARCH 2011<br />FEBRUARY 2011<br />JANUARY 2011</div>
        
	</div><!-- end cp_sidesection -->
    
<div class="cp_sidesection">
		<div class="cp_sidebarcircle"></div>
        <div class="cp_sidesectiontitle">CATEGORIES</div>
        <div class="cp_sidesubtitle"><br />TRENDING<br />
        SCIENCE<br />CULTURE<br />TECHNOLOGY<br />INNOVATION</div>
        
	</div><!-- end cp_sidesection --> 
    
    
<div class="cp_sidesection">   
   <div id="cp_search"><form action="/culturepulse_search" method="get" target="_blank">
<input type="text" name="field" class="searchfield" value="" />
</form><div id="cp_search_sm"><a href="#"><img src="/images/sidebar_search_btn_27-26.jpg" border="0" /></a></div>  
</div><!-- end cp_search --> 

<div class="cp_sidesection">
		<div class="cp_sidebarcircle"></div>
        <div class="cp_sidesectiontitle">RSS FEED</div>
       
        
	</div><!-- end cp_sidesection --> 
    
 <div class="cp_sidesection">
		<div class="cp_sidebarcircle"></div>
        <div class="cp_sidesectiontitle">FOLLOW US</div>
        <div class="cp_sidesubtitle">
        	<div class="sideicon"><a href="https://www.facebook.com/BrainReserve"><img src="/images/social_fb_icon.png" border="0" /></a></div>
        	<div class="sideicon"><a href="https://twitter.com/#!/PopcornBrains"><img src="/images/social_tw_icon.png" border="0" /></a></div>

        </div>
        
	</div><!-- end cp_sidesection --> 
    



    
</div><!-- end cp_sidebar -->

<div id="cp_footer">
  
  <div id="cp_footer_content">
          <div id="cp_left_footer_content">
            <h3>ABOUT US</h3><br/>
           The trends that Faith Popcorn’s BrainReserve has identified have animated everything from the caffeinated hegemony of Starbucks to the cultural squeeze on Wal-Mart to the explosion that is social media.  www.faithpopcorn.com	
            </div>
            
            
  	<div id="cp_mid_footer_content">
	<h3>CONTACT US</h3><br/>
	
	1 Dag Hammarskjold Plaza,<br/>
	New York, NY 10017<br/>
	hello@faithpopcorn.com<br/>
	+ 1 (212) 772 - 7787	
	</div>
    
    
	<div id="cp_right_footer_content">
            <h3>CONNECT</h3><br/>Keep in touch with us. 
	<a href="https://www.facebook.com/BrainReserve"><img src="/images/social_media/icon_fb_20-20.jpg" /></a> <a href="https://twitter.com/#!/PopcornBrains"><img src="/images/social_media/icon_twitter_20-20.jpg" /></a> 
	</div>
        
  </div><!-- end cp_footer_content -->
  
</div><!-- end cp_footer -->


</div>


</div>
</body>
</html>

app/views/pages/culturepulse_article.html.erb

<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml">
<head>
<meta http-equiv="Content-Type" content="text/html; charset=UTF-8" />
<title></title>
<link rel="stylesheet" href="/stylesheets/style_cp.css" type="text/css">
</head>

<body>

<div id="cp_linewrapper">
<div id="cp_logo">


    <div style="text-align:center; width:1216px; margin-left:auto; margin-right:auto;">
    <img id="Image-Maps_7201202090253555" src="/images/header_logo_culturepulse.png" usemap="#Image-Maps_7201202090253555" border="0" width="1216" height="177" alt="" />
    <map id="_Image-Maps_7201202090253555" name="Image-Maps_7201202090253555">
    <area shape="rect" coords="58,22,308,91" href="/" alt="" title=""    />
     </map>
   

    </div>
            


</div>
<div id="cp_areafill_article">

  <div id="cp_maincontentarea">
	  <div >
	    <% if @articles[0].present? %>
		  <img id="cp_article_image" src="<%= @articles[0].article_photo.url  if @articles[0].present? %>" />
	    <% end %>
	  </div>
	  <div id="cp_article_text"><%= @articles[0].content.html_safe if @articles[0].present? %></div><!-- end cp_maincontentarea -->
<br/><br/><br/><br/><br/><br/><br/><br/><br/><br/><br/><br/><br/><br/><br/><br/><br/><br/><br/><br/><br/><br/><br/><br/><br/><br/><br/><br/><br/><br/><br/><br/>
  </div>
</div><!-- end cp_areafill -->




<div id="cp_sidebar">
	<div class="cp_sidesection">
		<div class="cp_sidebarcircle"></div>
        <div class="cp_sidesectiontitle">SUBSCRIBE</div>
        <div class="cp_sidesubtitle">Get our daily newsletter</div>
        <div id="cp_subscribefield"><form>
<input type="text" name="field" class="subscribefield" value="" />
</form></div>
		<div class="cp_signup"><a href="#" target="_self"><img src="/images/sidebar_subscribe_signup_btn_103-27.jpg" border="0" /></a></div>
	</div><!-- end cp_sidesection -->
    
<div class="cp_sidesection">
		<div class="cp_sidebarcircle"></div>
        <div class="cp_sidesectiontitle">ARCHIVES</div>
        <div class="cp_sidesubtitle"><br />OCTOBER 2011<br />
        SEPTEMBER 2011<br />AUGUST 2011<br />JULY 2011<br />JUNE 2011<br />MAY 2011<br />APRIL 2011<br />MARCH 2011<br />FEBRUARY 2011<br />JANUARY 2011</div>
        
	</div><!-- end cp_sidesection -->
    
<div class="cp_sidesection">
		<div class="cp_sidebarcircle"></div>
        <div class="cp_sidesectiontitle">CATEGORIES</div>
        <div class="cp_sidesubtitle"><br />TRENDING<br />
        SCIENCE<br />CULTURE<br />TECHNOLOGY<br />INNOVATION</div>
        
	</div><!-- end cp_sidesection --> 
    
    
<div class="cp_sidesection">   
   <div id="cp_search"><form>
<input type="text" name="field" action="/culturepulse_search" class="searchfield" value="" />
</form><div id="cp_search_sm"><a href="#"><img src="/images/sidebar_search_btn_27-26.jpg" border="0" /></a></div>  
</div><!-- end cp_search --> 

<div class="cp_sidesection">
		<div class="cp_sidebarcircle"></div>
        <div class="cp_sidesectiontitle">RSS FEED</div>
       
        
	</div><!-- end cp_sidesection --> 
    
 <div class="cp_sidesection">
		<div class="cp_sidebarcircle"></div>
        <div class="cp_sidesectiontitle">FOLLOW US</div>
        <div class="cp_sidesubtitle">
        	<div class="sideicon"><a href="#"><img src="/images/social_fb_icon.png" border="0" /></a></div>
        	<div class="sideicon"><a href="#"><img src="/images/social_tw_icon.png" border="0" /></a></div>
         
        </div>
        
	</div><!-- end cp_sidesection --> 
    



    
</div><!-- end cp_sidebar -->

<div id="cp_footer">
  
  <div id="cp_footer_content">
          <div id="cp_left_footer_content">
            <h3>ABOUT US</h3><br/>
           The trends that Faith Popcorn’s BrainReserve has identified have animated everything from the caffeinated hegemony of Starbucks to the cultural squeeze on Wal-Mart to the explosion that is social media.  www.faithpopcorn.com	
            </div>
            
            
  	<div id="cp_mid_footer_content">
	<h3>CONTACT US</h3><br/>
	
	1 Dag Hammarskjold Plaza,<br/>
	New York, NY 10017<br/>
	hello@faithpopcorn.com<br/>
	+ 1 (212) 772 - 7787	
	</div>
    
    
	<div id="cp_right_footer_content">
            <h3>CONNECT</h3><br/>Keep in touch with us. 
            <img src="/images/social_media/icon_fb_20-20.jpg" /> <img src="/images/social_media/icon_tumblr_20-20.jpg" /> <img src="/images/social_media/icon_twitter_20-20.jpg" /> <img src="/images/social_media/icon_youtube_20-20.jpg" />
	</div>
        
  </div><!-- end cp_footer_content -->
  
</div><!-- end cp_footer -->


</div>


</div>
</body>
</html>

app/views/pages/culturepulse_search.html.erb

<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml">
<head>
<meta http-equiv="Content-Type" content="text/html; charset=UTF-8" />
<title></title>
<link rel="stylesheet" href="/stylesheets/style_cp.css" type="text/css">
</head>

<body>

<div id="cp_linewrapper">
<div id="cp_logo">


    <div style="text-align:center; width:1216px; margin-left:auto; margin-right:auto;">
    <img id="Image-Maps_7201202090253555" src="/images/header_logo_culturepulse.png" usemap="#Image-Maps_7201202090253555" border="0" width="1216" height="177" alt="" />
    <map id="_Image-Maps_7201202090253555" name="Image-Maps_7201202090253555">
    <area shape="rect" coords="58,22,308,91" href="/" alt="" title=""    />
     </map>
   

    </div>
            


</div>
<div id="cp_areafill_article">

  <div id="cp_maincontentarea">
	  
	  <div id="searchresults">
	        <% @articles.each do |article| %>   
		       <div>
			 <h2><span class="article_name"><a href="/culturepulse/article?name=<%= CGI.escape(article.name) %>"><%= article.name %></a></span></h2>  
			  <hr/>  <span class="article_description"><%= article.description %></span>
		      </div><br/><br/>
		<% end %>
	  </div>

<!-- end cp_maincontentarea -->
<br/><br/><br/><br/><br/><br/><br/><br/><br/><br/><br/><br/><br/><br/><br/><br/><br/><br/><br/><br/><br/><br/><br/><br/><br/><br/><br/><br/><br/><br/><br/><br/>
  </div>
</div><!-- end cp_areafill -->




<div id="cp_sidebar">
	<div class="cp_sidesection">
		<div class="cp_sidebarcircle"></div>
        <div class="cp_sidesectiontitle">SUBSCRIBE</div>
        <div class="cp_sidesubtitle">Get our daily newsletter</div>
        <div id="cp_subscribefield"><form>
<input type="text" name="field" class="subscribefield" value="" />
</form></div>
		<div class="cp_signup"><a href="#" target="_self"><img src="/images/sidebar_subscribe_signup_btn_103-27.jpg" border="0" /></a></div>
	</div><!-- end cp_sidesection -->
    
<div class="cp_sidesection">
		<div class="cp_sidebarcircle"></div>
        <div class="cp_sidesectiontitle">ARCHIVES</div>
        <div class="cp_sidesubtitle"><br />OCTOBER 2011<br />
        SEPTEMBER 2011<br />AUGUST 2011<br />JULY 2011<br />JUNE 2011<br />MAY 2011<br />APRIL 2011<br />MARCH 2011<br />FEBRUARY 2011<br />JANUARY 2011</div>
        
	</div><!-- end cp_sidesection -->
    
<div class="cp_sidesection">
		<div class="cp_sidebarcircle"></div>
        <div class="cp_sidesectiontitle">CATEGORIES</div>
        <div class="cp_sidesubtitle"><br />TRENDING<br />
        SCIENCE<br />CULTURE<br />TECHNOLOGY<br />INNOVATION</div>
        
	</div><!-- end cp_sidesection --> 
    
    
<div class="cp_sidesection">   
   <div id="cp_search"><form>
<input type="text" name="field" action="/culturepulse_search" class="searchfield" value="" />
</form><div id="cp_search_sm"><a href="#"><img src="/images/sidebar_search_btn_27-26.jpg" border="0" /></a></div>  
</div><!-- end cp_search --> 

<div class="cp_sidesection">
		<div class="cp_sidebarcircle"></div>
        <div class="cp_sidesectiontitle">RSS FEED</div>
       
        
	</div><!-- end cp_sidesection --> 
    
 <div class="cp_sidesection">
		<div class="cp_sidebarcircle"></div>
        <div class="cp_sidesectiontitle">FOLLOW US</div>
        <div class="cp_sidesubtitle">
        	<div class="sideicon"><a href="https://www.facebook.com/BrainReserve"><img src="/images/social_fb_icon.png" border="0" /></a></div>
        	<div class="sideicon"><a href="https://twitter.com/#!/PopcornBrains"><img src="/images/social_tw_icon.png" border="0" /></a></div>
          
        </div>
        
	</div><!-- end cp_sidesection --> 
    



    
</div><!-- end cp_sidebar -->

<div id="cp_footer">
  
  <div id="cp_footer_content">
          <div id="cp_left_footer_content">
            <h3>ABOUT US</h3><br/>
           The trends that Faith Popcorn’s BrainReserve has identified have animated everything from the caffeinated hegemony of Starbucks to the cultural squeeze on Wal-Mart to the explosion that is social media.  www.faithpopcorn.com	
            </div>
            
            
  	<div id="cp_mid_footer_content">
	<h3>CONTACT US</h3><br/>
	
	1 Dag Hammarskjold Plaza,<br/>
	New York, NY 10017<br/>
	hello@faithpopcorn.com<br/>
	+ 1 (212) 772 - 7787	
	</div>
    
    
	<div id="cp_right_footer_content">
            <h3>CONNECT</h3><br/>Keep in touch with us. 
            <img src="/images/social_media/icon_fb_20-20.jpg" /> <img src="/images/social_media/icon_tumblr_20-20.jpg" /> <img src="/images/social_media/icon_twitter_20-20.jpg" /> <img src="/images/social_media/icon_youtube_20-20.jpg" />
	</div>
        
  </div><!-- end cp_footer_content -->
  
</div><!-- end cp_footer -->


</div>


</div>
</body>
</html>

app/views/pages/edit.html.erb
<h1>Editing page</h1>

<%= render 'form' %>

<%= link_to 'Show', @page %> |
<%= link_to 'Back', pages_path %>

app/views/pages/index.html.erb
<h1>BrainReserve Site Administration</h1>

<table>
  <tr>
    <th></th>
    <th></th>
    <th></th>
  </tr>

</table>

<br />
<%= link_to 'Talent Bank Administration', talentbank_members_path %>
<%= link_to 'Articles Administration', articles_path %>

app/views/pages/new.html.erb
<h1>New page</h1>

<%= render 'form' %>

<%= link_to 'Back', pages_path %>

app/views/pages/show.html.erb
<p id="notice"><%= notice %></p>
<h2><%= @page.name %></h2><br/>
<%= @page.description %><br/>
<br/>

<h3>Snippets</h3><br/>
<table>
  <tr>
    <th>Name</th>
    <th>Description</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @snippets.each do |snippet| %>
  <tr>
    <td><%= snippet.name %></td>
    <td><%= snippet.description %></td>
   
    <td><%= link_to 'Show', page_snippet_path(@page, snippet) %></td>
    <td><%= link_to 'Edit', edit_page_snippet_path(@page, snippet) %></td>
    <td><%= link_to 'Destroy', page_snippet_path(@page, snippet), :confirm => 'Are you sure?', :method => :delete %></td>
  </tr>
<% end %>
</table>


<h3>Assets</h3><br/>

<table>
  <tr>
    <th>Name</th>
    <th>Description</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @assets.each do |asset| %>
  <tr>
    <td><%= asset.name %></td>
    <td><%= asset.description %></td>
    <td><%= link_to 'Show', page_asset_path(@page, asset) %></td>
    <td><%= link_to 'Edit', edit_page_asset_path(@page, asset) %></td>
    <td><%= link_to 'Destroy', page_asset_path(@page, asset), :confirm => 'Are you sure?', :method => :delete %></td>
  </tr>
<% end %>
</table>

<br/>



<%= link_to 'Snippets', page_snippets_path(@page) %>
<%= link_to 'Edit', edit_page_path(@page) %> |
<%= link_to 'Back', pages_path %>

app/views/pages/show_article.html.erb
<div id="main" >
  <div id="main_left">
    <h3><%= @article[0].name.to_s if @article[0].present? %></h3>
  </div>

  <div id="main_right">
  <center><h1> </h1> 
    <img src="<%= @article[0].article_photo.url if @article[0].present? %>" /> </center>
    
    <%= @article[0].content.html_safe if @article[0].present? %> 
   </div>

<% unless params[:show_comments] == "false" %>
  <div id="comment_form">
    <% if @article[0].present? and @new_comment.present? %>
	<%= form_for [@article[0], @new_comment] do |f| %>
	  <% if @new_comment.errors.any? %>
	    <div id="error_explanation">
	      <h2><%= pluralize(@new_comment.errors.count, "error") %> prohibited this snippet from being saved:</h2>

	      <ul>
	      <% @new_comment.errors.full_messages.each do |msg| %>
		<li><%= msg %></li>
	      <% end %>
	      </ul>
	    </div>
	  <% end %>
	  <div class="field">
	    <%= f.label :name %><br />
	    <%= f.text_field :name %>
	  </div>

	  <div class="field">
	    <%= f.label 'Comment' %><br />
	    <%= f.text_area :content %>
	  </div>
	  
	  <div class="actions">
	    <%= f.submit 'Submit Comment' %>
	  </div>
	<% end %>
    <% end %>
  </div>
<% end %>

   
</div>