config/routes.rb
Brainreserve::Application.routes.draw do
  
  resources :employees

  root :to => "pages#home"
  
  match '/admin' => 'pages#index'
   match '/pages/show_article' => 'pages#show_article'
  match 'culturepulse_search' => 'pages#culturepulse_search'
   match '/culturepulse/article' => 'pages#culturepulse_article'

   match '/culturepulse' => 'pages#culturepulse'
  
  devise_for :administrators, :path_prefix => 'd'

  resources :pages do
  	resources :assets
	resources :snippets
	
  end
  resources :talentbank_members
  resources :articles do
    resources :comments
  end

end

app/models/asset.rb
class Asset
  include Mongoid::Document
  include Mongoid::Paperclip

  field :name, :type => String
  field :description, :type => String
  has_mongoid_attached_file :asset_file
  referenced_in :page
  
  validates :name, :presence => true
  
end

app/controllers/assets_controller.rb
class AssetsController < ApplicationController
   before_filter :authenticate_administrator!
  
  
  
  
  # GET /assets
  # GET /assets.xml
  def index
    @page = Page.find(params[:page_id])
    @assets = @page.assets.all
    @assets = @assets.paginate(:page => params[:page], :per_page => 1)
   
    respond_to do |format|
      format.html # index.html.erb
      format.xml  { render :xml => @assets }
    end
  end

  # GET /assets/1
  # GET /assets/1.xml
  def show
      @page = Page.find(params[:page_id])
    @asset = @page.assets.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.xml  { render :xml => @asset }
    end
  end

  # GET /assets/new
  # GET /assets/new.xml
  def new
      @page = Page.find(params[:page_id])
    @asset = @page.assets.new

    respond_to do |format|
      format.html # new.html.erb
      format.xml  { render :xml => @asset }
    end
  end

  # GET /assets/1/edit
  def edit
      @page = Page.find(params[:page_id])
    @asset = @page.assets.find(params[:id])
  end

  # POST /assets
  # POST /assets.xml
  def create
      @page = Page.find(params[:page_id])
    @asset = @page.assets.new(params[:asset])

    respond_to do |format|
      if @asset.save
        format.html { redirect_to(page_url(@page), :notice => 'Asset was successfully created.') }
        format.xml  { render :xml => @asset, :status => :created, :location => @asset }
      else
        format.html { render :action => "new" }
        format.xml  { render :xml => @asset.errors, :status => :unprocessable_entity }
      end
    end
  end

  # PUT /assets/1
  # PUT /assets/1.xml
  def update
      @page = Page.find(params[:page_id])
    @asset = @page.assets.find(params[:id])

    respond_to do |format|
      if @asset.update_attributes(params[:asset])
        format.html { redirect_to(page_url(@page), :notice => 'Asset was successfully updated.') }
        format.xml  { head :ok }
      else
        format.html { render :action => "edit" }
        format.xml  { render :xml => @asset.errors, :status => :unprocessable_entity }
      end
    end
  end

  # DELETE /assets/1
  # DELETE /assets/1.xml
  def destroy
    @page = Page.find(params[:page_id])
    @asset = @page.assets.find(params[:id])
    @asset.destroy

    respond_to do |format|
      format.html { redirect_to(page_url(@page)) }
      format.xml  { head :ok }
    end
  end
end

app/helpers/assets_helper.rb
module AssetsHelper
end

app/views/assets/_form.html.erb
<%= form_for([@page, @asset], :html => {:multipart => true}) do |f| %>
  <% if @asset.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@asset.errors.count, "error") %> prohibited this asset from being saved:</h2>

      <ul>
      <% @asset.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br />
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :description %><br />
    <%= f.text_area :description %>
  </div>
  
  <div class="field">
    <%= f.label 'Asset file' %><br />
    <%= f.file_field :asset_file %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<!-- this hack allows us to get around the javascript-file system restriction to allow us to perform AJAX uploads successfully -->

<% end %>

app/views/assets/edit.html.erb
<h1>Editing asset</h1>

<%= render 'form' %>

<%= link_to 'Show', page_asset_path(@page, @asset) %> |
<%= link_to 'Back', page_assets_path(@page) %>

app/views/assets/index.html.erb
<h1>Listing assets</h1>

<table>
  <tr>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @assets.each do |asset| %>
  <tr>
    <td><%= asset.name %></td>
    <td><%= asset.description %></td>
    <td><%= link_to 'Show', page_asset_path(@page, asset) %></td>
    <td><%= link_to 'Edit', edit_page_asset_path(@page, asset) %></td>
    <td><%= link_to 'Destroy', page_asset_path(@page, asset), :confirm => 'Are you sure?', :method => :delete %></td>
  </tr>
<% end %>
</table>

<br />
<%= will_paginate @assets %>

<%= link_to 'New Asset', new_page_asset_path(@page) %>

app/views/assets/new.html.erb
<h1>New asset</h1>

<%= render 'form' %>

<%= link_to 'Back', page_assets_path(@page) %>

app/views/assets/show.html.erb
<p id="notice"><%= notice %></p>


<%= link_to 'Edit', edit_page_asset_path(@page, @asset) %> |
<%= link_to 'Back', page_assets_path(@page) %>